parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
settings:
  import/resolver:
    node:
      extensions: ['.ts']
rules:
  import/prefer-default-export: off
