language: node_js
node_js:
  - 10
cache: yarn
script:
  - yarn build
  - yarn style:check
  - yarn lint
  - yarn test
deploy:
  provider: npm
  email: mattfysh@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
